sources_uses_consildated = {
    "FTEs": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Beginning Balance (Contingency Reserve)": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "UNRESTRICTED REVENUE": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Property Taxes": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Lease Revenue": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Tobacco Litigation Settlement": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Patient Revenue": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Other": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "TOTAL UNRESTRICTED REVENUE": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "RESTRICTED REVENUE": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Opioid Litigation Settlement(1)": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "ALL REVENUE TOTAL": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Available Budgeted Resources": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "EXPENSES": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Healthcare Delivery": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Administration": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "UT Affiliation Agreement": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Other Financing Uses": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Opioid Abatement Expenses(1)": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Contingency Reserves": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Total Expenses": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Increase/Decrease in Fund Balance": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Ending Contingency Reserve Balance": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "RESERVES": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
    "Emergency Reserves": {
        "IsSubTotal": False,
        "Value": 0,
        "BusinessUnit": None,
        "Account": None,
        "RAD": None,
    },
}
